# Generated by Django 4.2.7 on 2023-11-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('codigo', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_carrera', models.TextField(max_length=8)),
                ('nombre_carrera', models.TextField(max_length=60)),
                ('codigo_titulo', models.TextField(max_length=20)),
                ('descripcion_titulo', models.TextField(max_length=200)),
                ('nivel', models.CharField(choices=[('LICENCIATURA', 'LICENCIATURA'), ('TECNICO SUPERIOR', 'TECNICO SUPERIOR'), ('TECNICO MEDIO', 'TECNICO MEDIO')], max_length=20)),
                ('estado', models.TextField(max_length=1)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tituloprovision.facultad')),
            ],
        ),
    ]
