# Generated by Django 4.2.7 on 2023-11-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tituloprovision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultad',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nomenclatura',
            name='codigo_titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nomenclatura',
            name='descripcion_titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nomenclatura',
            name='estado',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='nomenclatura',
            name='nombre_carrera',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='nomenclatura',
            name='plan_carrera',
            field=models.CharField(max_length=8),
        ),
    ]
